name: terraresin_core
description: Core utilities and shared functionality for TerraResin applications.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.13.3
  flutter: ">=3.47.4"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0